Update `future`  to version `1.18.3`
AnacondaRecipes/future-feedstock pull request #2
Opened 2023-02-16 21:48 UTC by varlackc

`future` version `0.18.3`
1. - [X] Check the upstream
    https://github.com/PythonCharmers/python-future/tree/v0.18.3
2. - [_] Check the pinnings
3. - [X] Check the changelogs
    https://github.com/PythonCharmers/python-future/blob/v0.18.3/docs/whatsnew.rst

4. - [X] Additional research
    https://github.com/conda-forge/future-feedstock/issues
    
There are currently no open issues mentioned at the time of the review in conda forge
5. - [X] Verify the `dev_url`
    https://github.com/PythonCharmers/python-future
6. - [X] Verify the `doc_url`
    http://python-future.org
    
    The `doc_url` seems to have issues an eye must be kept on the package until a new `doc_url` is specified

7. - [X] License is `spdx` compliant
    MIT
8. - [X] License family is present
    MIT
9. - [X] Verify that the `build_number` is correct
10. - [X] Verify if the package needs `setuptools`
    
11. - [X] Verify if the package needs `wheel`
    Wheel does not seem to be mentioned
12. - [X] `pip` in the test section
    pip
13. - [X] Veriy the test section
14. - [X] Verify if the package is `architecture specific` or `Noarch`
15. - [X] Verify that private modules are not mentioned on the recipe For example: (_private_module)
 
Results:
- 
 
 
Based on the research findings and the results we can conclude
that it is safe to update `future` to version `0.18.3`

2023-02-16 21:49 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_19lcgoj70h/clone/recipe/meta.yaml:23: missing_wheel: For pypi packages, wheel should be present in the host section
ERROR: /tmp/abs_19lcgoj70h/clone/recipe/meta.yaml:51: http_url: http://python-future.org is not https
Errors were found

</details>

2023-02-20 16:14 UTC, chenghlee commented on recipe/meta.yaml
> +    - libpasteurize
I'm not sure these `lib*` modules are meant to be directly imported by the user; they seem more like support for the `futurize` and `pasteurize` scripts. If that's the case, we should just remove them from the `imports` tests.

2023-02-22 19:40 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_0bdfuk3by1/clone/recipe/meta.yaml:23: missing_wheel: For pypi packages, wheel should be present in the host section
ERROR: /tmp/abs_0bdfuk3by1/clone/recipe/meta.yaml:47: http_url: http://python-future.org is not https
Errors were found

</details>

2023-02-23 21:05 UTC, chenghlee requested changes

2023-02-23 21:05 UTC, chenghlee commented on recipe/meta.yaml
> +    - pip check
The `futurize -h` and `pasteurize -h` commands should still be kept. We (probably) just don't need to test the import of their corresponding `lib*` modules.

2023-02-23 21:08 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_a4xidu8kh1/clone/recipe/meta.yaml:23: missing_wheel: For pypi packages, wheel should be present in the host section
ERROR: /tmp/abs_a4xidu8kh1/clone/recipe/meta.yaml:49: http_url: http://python-future.org is not https
Errors were found

</details>

2023-02-23 21:08 UTC, chenghlee approved these changes

2023-02-27 20:54 UTC, sumit0190 approved these changes

2023-02-28 07:26 UTC, skupr-anaconda commented on recipe/meta.yaml
>    home: http://python-future.org
`home` and `doc_url` should have HTTPS

2023-02-28 15:45 UTC, varlackc commented on recipe/meta.yaml
>    home: http://python-future.org
the urls were updated

2023-02-28 15:45 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_b86_edippe/clone/recipe/meta.yaml:23: missing_wheel: For pypi packages, wheel should be present in the host section
Errors were found

</details>

2023-02-28 15:57 UTC, merged

2023-02-28 15:57 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: /tmp/abs_2eps2y_39f/clone/recipe/meta.yaml:23: missing_wheel: For pypi packages, wheel should be present in the host section
Errors were found

</details>